# Convolution layer from scratch (The forward pass)

In this example we first try to implement the conv forward function for single channel images, then we move on to RGB images.

### Single channel convolution

In [1]:
import numpy as np
def conv_2d(x, kernel, bias, Padding=0, stride=1):
    kernel_shape = kernel.shape[0]
    output_shape = int((x.shape[0] +2 * Padding - kernel_shape ) / stride + 1)
    result = np.zeros((output_shape, output_shape))
    for row in range((x.shape[0] +2 * Padding -kernel_shape)//stride + 1):
        for col in range((x.shape[1] +2 * Padding -kernel_shape)//stride + 1):
            window = x[row: row + kernel_shape, col: col + kernel_shape]
            result[row, col] = np.sum(np.multiply(kernel,window))
    return result + bias

In [2]:
input_matrix = np.array([[3., 9., 0.],[2., 8., 1.],[1., 4., 8.]])
kernel = np.array([[8., 9.],[4., 4.]])
bias = np.array([0.06])
print('input_matrix.shape',input_matrix.shape)
print('kernel.shape',kernel.shape)
print('bias.shape',bias.shape)

input_matrix.shape (3, 3)
kernel.shape (2, 2)
bias.shape (1,)


In [3]:
def im2col(x, kernel):
    kernel_shape = kernel.shape[0]
    rows = []
    
    # Assuming Padding = 0, stride = 1
    for row in range(x.shape[0] - 1):
        for col in range(x.shape[1] - 1):
            window = x[row: row + kernel_shape, col: col + kernel_shape]
            rows.append(window.flatten())
            
    return np.transpose(np.array(rows))

In [4]:
output_shape = (input_matrix.shape[0] - kernel.shape[0]) + 1
im2col_matrix = im2col(input_matrix, kernel) 
print('im2col_matrix.shape',im2col_matrix.shape)
print('kernel.flatten().shape',kernel.flatten().shape)
im2col_conv = np.dot(kernel.flatten(), im2col_matrix) + bias
im2col_conv = im2col_conv.reshape(output_shape,output_shape)
print(im2col_conv)

naive_conv_op = conv_2d(input_matrix, kernel, bias)
print(np.array_equal(im2col_conv,naive_conv_op))

im2col_matrix.shape (4, 4)
kernel.flatten().shape (4,)
[[145.06 108.06]
 [108.06 121.06]]
True


### Single channel max pooling

In [5]:
def maxpool_2d(x, kernelsz, stride=2):
    kernel_shape = kernelsz[0]
#     output_shape = int((x.shape[0] +2 * Padding - kernel_shape ) / stride + 1)
    output_shape = int((x.shape[0] - kernel_shape ) / stride + 1)
    result = np.zeros((output_shape, output_shape))
    for row in range((x.shape[0] - kernel_shape)//stride+1):
        for col in range((x.shape[1] - kernel_shape)//stride+1):
            window = x[row*stride: row*stride + kernel_shape, col*stride: col*stride + kernel_shape]
            result[row, col] = np.max(window)
    return result
input_matrix = np.array([[3., 9., 0., 4.],[2., 8., 1., 1.],[1., 4., 8., 1.],[7., 4., 8., 9.]])
naive_pool_op = maxpool_2d(input_matrix, (2,2))

In [6]:
input_matrix

array([[3., 9., 0., 4.],
       [2., 8., 1., 1.],
       [1., 4., 8., 1.],
       [7., 4., 8., 9.]])

In [7]:
naive_pool_op

array([[9., 4.],
       [7., 9.]])